#############################################################################
# Makefile for building: languageapplet
# Generated by qmake (2.01a) (Qt 4.7.4) on: Sun Apr 14 00:32:44 2013
# Project:  languageapplet.pro
# Template: subdirs
# Command: /usr/bin/qmake CONFIG+=markuntranslated CONFIG+=harmattan QMAKE_CXXFLAGS=-g\ -O2\ -Wall\ -g\ -O2\ -DPUBLIC_RELEASE -o Makefile languageapplet.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-display

display/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) display/ || $(MKDIR) display/ 
	cd display/ && $(QMAKE) /home/tomek/powerpack/duicc/meegotouch-meegotouch-controlpanellanguageapplet/display/display.pro CONFIG+=markuntranslated CONFIG+=harmattan QMAKE_CXXFLAGS=-g\ -O2\ -Wall\ -g\ -O2\ -DPUBLIC_RELEASE -o $(MAKEFILE)
sub-display-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) display/ || $(MKDIR) display/ 
	cd display/ && $(QMAKE) /home/tomek/powerpack/duicc/meegotouch-meegotouch-controlpanellanguageapplet/display/display.pro CONFIG+=markuntranslated CONFIG+=harmattan QMAKE_CXXFLAGS=-g\ -O2\ -Wall\ -g\ -O2\ -DPUBLIC_RELEASE -o $(MAKEFILE)
sub-display: display/$(MAKEFILE) FORCE
	cd display/ && $(MAKE) -f $(MAKEFILE)
sub-display-make_default: display/$(MAKEFILE) FORCE
	cd display/ && $(MAKE) -f $(MAKEFILE) 
sub-display-make_first: display/$(MAKEFILE) FORCE
	cd display/ && $(MAKE) -f $(MAKEFILE) first
sub-display-all: display/$(MAKEFILE) FORCE
	cd display/ && $(MAKE) -f $(MAKEFILE) all
sub-display-clean: display/$(MAKEFILE) FORCE
	cd display/ && $(MAKE) -f $(MAKEFILE) clean
sub-display-distclean: display/$(MAKEFILE) FORCE
	cd display/ && $(MAKE) -f $(MAKEFILE) distclean
sub-display-install_subtargets: display/$(MAKEFILE) FORCE
	cd display/ && $(MAKE) -f $(MAKEFILE) install
sub-display-uninstall_subtargets: display/$(MAKEFILE) FORCE
	cd display/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: languageapplet.pro  /targets/HARMATTAN_ARMEL/usr/share/qt4/mkspecs/linux-g++-maemo/qmake.conf /targets/HARMATTAN_ARMEL/usr/share/qt4/mkspecs/common/g++.conf \
		/targets/HARMATTAN_ARMEL/usr/share/qt4/mkspecs/common/unix.conf \
		/targets/HARMATTAN_ARMEL/usr/share/qt4/mkspecs/common/linux.conf \
		/targets/HARMATTAN_ARMEL/usr/share/qt4/mkspecs/qconfig.pri \
		/targets/HARMATTAN_ARMEL/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/targets/HARMATTAN_ARMEL/usr/share/qt4/mkspecs/features/qt_config.prf \
		/targets/HARMATTAN_ARMEL/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/targets/HARMATTAN_ARMEL/usr/share/qt4/mkspecs/features/default_pre.prf \
		/targets/HARMATTAN_ARMEL/usr/share/qt4/mkspecs/features/debug.prf \
		/targets/HARMATTAN_ARMEL/usr/share/qt4/mkspecs/features/default_post.prf \
		/targets/HARMATTAN_ARMEL/usr/share/qt4/mkspecs/features/silent.prf \
		/targets/HARMATTAN_ARMEL/usr/share/qt4/mkspecs/features/warn_on.prf \
		/targets/HARMATTAN_ARMEL/usr/share/qt4/mkspecs/features/qt.prf \
		/targets/HARMATTAN_ARMEL/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/targets/HARMATTAN_ARMEL/usr/share/qt4/mkspecs/features/moc.prf \
		/targets/HARMATTAN_ARMEL/usr/share/qt4/mkspecs/features/resources.prf \
		/targets/HARMATTAN_ARMEL/usr/share/qt4/mkspecs/features/uic.prf \
		/targets/HARMATTAN_ARMEL/usr/share/qt4/mkspecs/features/yacc.prf \
		/targets/HARMATTAN_ARMEL/usr/share/qt4/mkspecs/features/lex.prf \
		/targets/HARMATTAN_ARMEL/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) CONFIG+=markuntranslated CONFIG+=harmattan QMAKE_CXXFLAGS=-g\ -O2\ -Wall\ -g\ -O2\ -DPUBLIC_RELEASE -o Makefile languageapplet.pro
/targets/HARMATTAN_ARMEL/usr/share/qt4/mkspecs/common/g++.conf:
/targets/HARMATTAN_ARMEL/usr/share/qt4/mkspecs/common/unix.conf:
/targets/HARMATTAN_ARMEL/usr/share/qt4/mkspecs/common/linux.conf:
/targets/HARMATTAN_ARMEL/usr/share/qt4/mkspecs/qconfig.pri:
/targets/HARMATTAN_ARMEL/usr/share/qt4/mkspecs/features/qt_functions.prf:
/targets/HARMATTAN_ARMEL/usr/share/qt4/mkspecs/features/qt_config.prf:
/targets/HARMATTAN_ARMEL/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/targets/HARMATTAN_ARMEL/usr/share/qt4/mkspecs/features/default_pre.prf:
/targets/HARMATTAN_ARMEL/usr/share/qt4/mkspecs/features/debug.prf:
/targets/HARMATTAN_ARMEL/usr/share/qt4/mkspecs/features/default_post.prf:
/targets/HARMATTAN_ARMEL/usr/share/qt4/mkspecs/features/silent.prf:
/targets/HARMATTAN_ARMEL/usr/share/qt4/mkspecs/features/warn_on.prf:
/targets/HARMATTAN_ARMEL/usr/share/qt4/mkspecs/features/qt.prf:
/targets/HARMATTAN_ARMEL/usr/share/qt4/mkspecs/features/unix/thread.prf:
/targets/HARMATTAN_ARMEL/usr/share/qt4/mkspecs/features/moc.prf:
/targets/HARMATTAN_ARMEL/usr/share/qt4/mkspecs/features/resources.prf:
/targets/HARMATTAN_ARMEL/usr/share/qt4/mkspecs/features/uic.prf:
/targets/HARMATTAN_ARMEL/usr/share/qt4/mkspecs/features/yacc.prf:
/targets/HARMATTAN_ARMEL/usr/share/qt4/mkspecs/features/lex.prf:
/targets/HARMATTAN_ARMEL/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) CONFIG+=markuntranslated CONFIG+=harmattan QMAKE_CXXFLAGS=-g\ -O2\ -Wall\ -g\ -O2\ -DPUBLIC_RELEASE -o Makefile languageapplet.pro

qmake_all: sub-display-qmake_all FORCE

make_default: sub-display-make_default FORCE
make_first: sub-display-make_first FORCE
all: sub-display-all FORCE
clean: sub-display-clean FORCE
distclean: sub-display-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-display-install_subtargets FORCE
uninstall_subtargets: sub-display-uninstall_subtargets FORCE

sub-display-check: display/$(MAKEFILE)
	cd display/ && $(MAKE) check
check: sub-display-check

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

